-- Vell Print Technology SQL Schema Initialization (Oracle Database)
-- Execute this script in your SQL Developer, SQL*Plus, or OCI Database Actions console.

-- 1. Create table for Admin Users
CREATE TABLE admin_users (
    username VARCHAR2(50) PRIMARY KEY,
    password_hash VARCHAR2(255) NOT NULL
);

-- 2. Create table for Offers
CREATE TABLE offers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    image_path VARCHAR2(255),
    discount VARCHAR2(50) NOT NULL,
    start_date VARCHAR2(50),
    end_date VARCHAR2(50),
    is_active NUMBER(1) DEFAULT 1
);

-- 3. Create table for Production Gallery Items
CREATE TABLE gallery (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100),
    image_path VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed Initial Default Admin User (Default login: admin / admin123)
-- Password hash generated using bcryptjs: '$2a$10$8CgDk1Hj71rF2Ue/Hl8MSeUu209nI4e72vLd1TzM.27bH4Bq.rP2i'
INSERT INTO admin_users (username, password_hash) 
VALUES ('admin', '$2a$10$8CgDk1Hj71rF2Ue/Hl8MSeUu209nI4e72vLd1TzM.27bH4Bq.rP2i');

COMMIT;

-- Verification Queries
SELECT table_name FROM user_tables;
SELECT * FROM admin_users;
